/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Convert an RGB color (0-255) to a normalized RGB color (0.0-1.0)
 *
 * # Arguments
 * * `color` - The RGB color
 *
 * # Returns
 * The normalized RGB color
 */
export declare function colorToNormalized(color: RgbColor): NormalizedRgbColor

/**
 * Composite an RGBA pixel over an RGB background color
 *
 * If the input pixel is translucent (alpha < 255), this pre-composes it over
 * the background color to produce an opaque equivalent.
 *
 * # Arguments
 * * `pixel` - The RGBA pixel color
 * * `background` - The background RGB color
 *
 * # Returns
 * The composited RGB color
 */
export declare function compositeOverBackground(pixel: RgbaColor, background: RgbColor): RgbColor

/**
 * Compute the final color from unmix result
 *
 * # Arguments
 * * `weights` - The weights for each foreground color
 * * `alpha` - The alpha value
 * * `foreground_colors` - The foreground colors
 *
 * # Returns
 * The computed RGBA color
 */
export declare function computeUnmixResultColor(weights: Array<number>, alpha: number, foregroundColors: Array<RgbColor>): RgbaColor

/**
 * Detect the background color of an image by sampling its edges
 *
 * # Arguments
 * * `input` - The input image buffer
 *
 * # Returns
 * The detected background color
 */
export declare function detectBackgroundColor(input: Buffer): RgbColor

/**
 * Get the default threshold for color closeness
 *
 * # Returns
 * The default threshold (0.05 = 5% of max RGB distance)
 */
export declare function getDefaultThreshold(): number

export interface NormalizedRgbColor {
  r: number
  g: number
  b: number
}

/**
 * Convert a normalized RGB color (0.0-1.0) to an RGB color (0-255)
 *
 * # Arguments
 * * `color` - The normalized RGB color
 *
 * # Returns
 * The RGB color
 */
export declare function normalizedToColor(color: NormalizedRgbColor): RgbColor

/**
 * Parse a hex color string into an RGB color
 *
 * Supports formats: "#ff0000", "ff0000", "#f00", "f00"
 *
 * # Arguments
 * * `hex` - The hex color string
 *
 * # Returns
 * The parsed RGB color
 */
export declare function parseColor(hex: string): RgbColor

/**
 * Process an image asynchronously to remove its background
 *
 * Supports automatic background detection, foreground color deduction using "auto",
 * and both strict and non-strict processing modes.
 *
 * # Arguments
 * * `options` - The options for the image processing
 *
 * # Returns
 * A promise that resolves to the processed image buffer (PNG format)
 */
export declare function processImage(options: ProcessImageOptions): Promise<Buffer>

export interface ProcessImageOptions {
  /** The input image buffer */
  input: Buffer
  /** The foreground colors to match, if any. Use "auto" to deduce unknown colors. */
  foregroundColors?: Array<string>
  /** The background color to remove. If not specified, it will be auto-detected. */
  backgroundColor?: string
  /** Whether to use strict mode. Restricts unmixing to only the specified foreground colors. */
  strictMode: boolean
  /** The threshold for color closeness (0.0-1.0, default: 0.05) */
  threshold?: number
  /** Whether to trim the output image to the bounding box of non-transparent pixels */
  trim: boolean
}

/**
 * Process an image synchronously to remove its background
 *
 * Supports automatic background detection, foreground color deduction using "auto",
 * and both strict and non-strict processing modes.
 *
 * # Arguments
 * * `options` - The options for the image processing
 *
 * # Returns
 * The processed image buffer (PNG format)
 */
export declare function processImageSync(options: ProcessImageOptions): Buffer

export interface RgbaColor {
  r: number
  g: number
  b: number
  a: number
}

export interface RgbColor {
  r: number
  g: number
  b: number
}

/**
 * Trim the image to the bounding box of non-transparent pixels
 *
 * # Arguments
 * * `input` - The input image buffer
 *
 * # Returns
 * The trimmed image buffer (PNG format)
 */
export declare function trimImage(input: Buffer): Buffer

/**
 * Unmix an observed color into foreground color components
 *
 * Given an observed color and known foreground/background colors,
 * determines how much of each foreground color contributed to the observed color.
 *
 * # Arguments
 * * `observed` - The observed color
 * * `foreground_colors` - The foreground colors to match
 * * `background` - The background color
 *
 * # Returns
 * The unmix result containing weights for each foreground color and overall alpha
 */
export declare function unmixColor(observed: RgbColor, foregroundColors: Array<RgbColor>, background: RgbColor): UnmixResultJs

export interface UnmixResultJs {
  /** The weights for each foreground color */
  weights: Array<number>
  /** The alpha value */
  alpha: number
}
